# Generated by Django 5.2.8 on 2025-11-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_age_user_ban_activity_tile_tileoperation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tile',
            constraint=models.UniqueConstraint(fields=('x', 'y'), name='unique_tile_xy'),
        ),
    ]
